# Generated by Django 4.0.4 on 2022-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_like_count_post_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='like_count'),
        ),
    ]
